### ISSUE TITLE
#1 plant list

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#1]
# Plant List

## Value Proposition

**As a user**

**I want to** browse a list of plants,

**so that** I can discover new plants and learn about their care requirements.

## Description

<img src="https://github.com/user-attachments/assets/91e5a91a-35ab-4655-ba62-d4fcacbbed39" width="300" height="auto" />

## Acceptance Criteria

- The homepage displays a list of plants.
- The plant list is headlined with its purpose.
- Each plant listing includes:
  - Plant name
  - Plant botanical name
  - Plant image
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/plant-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/plants.json)
  - [ ] Add an `imageUrl` for each plant, for example from [unsplash.com](unsplash.com)
  - [ ] Add example data as data.js with individual URL to project
- [ ] Implement state "initialPlants" to store data
- [ ] Add headline "Plant List"
- [ ] Create PlantCard component as representational comp
- [ ] Map PlantCard for each plant "initialPlants" on HomePage
- [ ] Style container for PlantCards using flexbox and align content vertically

**Comment by jan-riemenschneider** [comment]
test

**Comment by JessicaLoers** [comment]
Well done ✅
