### ISSUE TITLE
#9 - Improve representation of form ✅

### ISSUE THREAD

**Issue by carmen136** [StephMode/plant-pal#14]
## Value Proposition

As a user
I want to have clear visual guidance
so that I know exactly where to add plants 

## Description

![Image](https://github.com/user-attachments/assets/baccbc99-ff84-4f67-99f5-96aaf5f73ed7)

[US 9 wireframe .pdf](https://github.com/user-attachments/files/17676224/US.9.wireframe.pdf)

## Acceptance Criteria
- There is a clickable `button` on the HomePage which calls the form
- There is a `button` to cancel and close the form at any time.
- The button is labelled so that the user understands that it leads to the form to add plants
- Primarily, an icon shall signify what the button does and the text-content describing the button shall be simple.
- Upon successful submission of the form, the modal shall be closed.
- Upon submission of an invalid form, the form shall provide validation error notifications using default browser behavior

## Tasks

- [ ] Create feature branch `name-feature-improve-represenation-of-form`
- [ ] Within the navbar, create a `AddPlant - button` to toggle the Form component
- [ ] Reuse the 'Modal' component for the representation of the form inside of a modal

**Comment by Roland-Hufnagel** [comment]
LGTM

**Comment by levinthiel** [comment]
Is obsolete
