### ISSUE TITLE
#10 - Improve features of the form ✔

### ISSUE THREAD

**Issue by carmen136** [StephMode/plant-pal#15]
## Value Proposition

*Only visual feedback*
As a user
I want to have clear visual feedback
so that I now wether I added a plant successfully or not

*Vsual feedback + mark added plant as owned*
As a user
I want to have clear visual signals
so that I now wether I added a plant successfully or not

## Description

![Image](https://github.com/user-attachments/assets/f5d9414d-8289-475c-a243-4df9eba8c288)

## Acceptance Criteria
- The shall be a message upon successfull form submission in the UI
- There shall be a customized message in case the user left one or more `required` input fields unfilled
- Upon form submission
  - if `required` inputs fields havn't been filled out, there shall be a pop up notificification to ask the user to do so.
  - if user provided valid input to all input fields, there shall be a toast message indicating that a plant has been added to the database successfully.
 - The text-content of the notifications shall be phrased in user-friendly way avoiding technical terminology.

## Tasks

- [ ] Create feature branch `name-feature-improve-functionality-of-form`
- [ ] Implement toast message on the `HomePage` upon successfull submission of the form
- [ ] Reuse the 'Modal' component for the valdiation error message

**Comment by E-LeeSchaffer** [comment]
On the last wireframe is a 'click' on My Plants: Is that a mistake? Or why should the user click on this navigation button?

Regarding 'The**re** shall be a message upon successfull form submission in the UI': Please add in the AC that the success message is a toast message. Otherwise it is not clear for how long the message will be shown. 

Regarding 'There shall be a customized message in case the user left one or more required input fields unfilled': I would suggest to make aware of the required field in the form next oder under the input field directly. I think it's more user-friendly as you have to click away the modal and search for the required field and click in the respective input field again. 

Regarding 'Create feature branch name-feature-improve-functionality-of-form': feature/improve-functionality-of-form would be nicer.

In General: You have the navigation menu. It would be user-friendly to highlight the current page.

**Comment by StephMode** [comment]
> On the last wireframe is a 'click' on My Plants: Is that a mistake? Or why should the user click on this navigation button?

That was indeed a mistake. We corrected the wireframe accordingly.

> Regarding 'The**re** shall be a message upon successfull form submission in the UI': Please add in the AC that the success message is a toast message. Otherwise it is not clear for how long the message will be shown.

Good point. We have specified the Acceptance Criteria accordingly.

> Regarding 'There shall be a customized message in case the user left one or more required input fields unfilled': I would suggest to make aware of the required field in the form next oder under the input field directly. I think it's more user-friendly as you have to click away the modal and search for the required field and click in the respective input field again.

Good point. We have changed the US in a way so that in both cases (validation error & successful form submission) a toast message will be displayed.

> Regarding 'Create feature branch name-feature-improve-functionality-of-form': feature/improve-functionality-of-form would be nicer.

Thanks for the hint. As this is the naming convention we decided upon in our team, we would like to stick with our branch naming style.

> In General: You have the navigation menu. It would be user-friendly to highlight the current page.

Absolutely. We changed the wireframe accordingly.

**Comment by JessicaLoers** [comment]
**Well done 🥁**

**Comment by StephMode** [comment]
According to Jessica, we are free to use libraries such as "toastify":

[npm page of toastify](https://www.npmjs.com/package/react-toastify)

**Comment by StephMode** [comment]
We could also use:

https://react-hot-toast.com/

**Comment by StephMode** [comment]
We could also change the name of the function 'handleSubmitAddPlant' here to something like 'handleSubmitForm' or anything that better reflects the multi-purpose-nature of the component.
