### ISSUE TITLE
#11 - Create solid styling for the app ✅

### ISSUE THREAD

**Issue by carmen136** [StephMode/plant-pal#16]
# Styling the app

## Value Proposition

As a plant buff

I want to browse a well styled app

so that I can enjoy my stay and use the app more easily as well

## Description

![Image](https://github.com/user-attachments/assets/5ae5d6a2-aeb3-4717-a62c-f2fb0c5d3ba7)

## Acceptance Criteria

- The app has a consistent styling through the app
- The app is responsive, and displays plants as a grid on desktop and automatically as a 2x list on mobile
- The buttons have a good size for mobile (min 48x48px)
- The colours are spread through the app according to our colour palette
- inputs, textareas have consistent behaviour
- add hover feedback on buttons for desktop usage
- have the correct Fonts implemented

## Tasks

- [x] Create feature branch `{name}-feature-11-overall-styling`
- [x] Use globalstyles and also styled components
- [x]  use grid for the plantCards on the homepage
  - [x]  `gap: 16px;`
          `padding: 24px;`
          `display: grid;`
          `list-style: none;`
          `grid-template-columns: repeat(auto-fill, minmax(327px, 1fr));`
- [x] Design `PlantDetails`
- [x] Design Filter
- [x] add a min height and min width for buttons
- [x] Implement favicon
- [x] replace the placeholder img
- [x] style the PlantCards so that long `plantName` do not influence the represenation of the `PlantCard`s
- [x] style the focused state of inputs and textareas
- [x] use &:hover { } on buttons and other elements
- [x] Improve `Form` Design
  - [x] colors and layout according to CI
  - [x] change icons for texts for the input fields
- [x] import the fonts, so the console doesn't give out and alert (local import?)

**Comment by Roland-Hufnagel** [comment]
LGTM.
you can add the fonts you want to use.
