### ISSUE TITLE
#12 - Page with tips for plant care ✅ ⏺️⏺️⏺️⏺️

### ISSUE THREAD

**Issue by carmen136** [StephMode/plant-pal#17]
# Page with tips for plant care

## Value Proposition

As a plant friend

I want to have a page with tips,

so that I can better take care of my plants.

## Description

![Image](https://github.com/user-attachments/assets/6c0371e6-5ee2-4211-9e9b-1a466fbba025)

## Acceptance Criteria

- The Navbar contains a link to a page that contains "Plant Tips".
- The page "Plant Tips" displays a list of single tips.
- The list is headlined with its purpose.
- Each item on page "Plant Tips" includes:
  - Tip name
  - A short description
  - An image
- The list supports vertical scrolling to accommodate multiple entries.
- Each Link on the page "Plant Tips" links to the single tip details page.

## Tasks

- [x] create feature branch `{name}-feature-#-tip-list`
- [x] add example data as `tipdata.js` containing data for the single "Plant Tips" content pieces as an array of objects
- [x] create a page fpr "Plant Tips"
  - [x] add headline
  - [x] add Link to Navbar for "Plant Tips" page
- [x] reuse PlantCard component as representational comp for objects in `tipdata.js`
- [x] map `PlantTip` for each object in `tipdata.js`
- [x] add dynamic route to `PlantTipsDetailPage` for single `PlantTip`on "Plant Tips" page

**Comment by ana-nova** [comment]
- Since you are using the footer as navigation, you should also mention, either as the first or last point, that the "plant tips" icon itself is displayed there.
- Regarding "cards link to articles and content pieces": the wording here is confusing. As a user, am I directed to a completely different page when I click on it, or is it meant as you fetch data from some articles?
- Optional: In your wireframe, you use two different labels: the "Plant tips" icon is labeled "`Plant tips`" while the page itself is called "`Tip list`" For consistency, you may want to name them the same, at least in the title.
- Also optional: According to you wireframe it's not visible that it's a slider. Maybe you can show `< >`  on the sides or `...` in the middle that the user can do here something.

**Comment by StephMode** [comment]
Hi @ana-nova , thanks a lot for your feedback :) We will revise the US and consider your feedback.

**Comment by StephMode** [comment]
> * Since you are using the footer as navigation, you should also mention, either as the first or last point, that the "plant tips" icon itself is displayed there.

Good point. We added it to the list of tasks.

> * Regarding "cards link to articles and content pieces": the wording here is confusing. As a user, am I directed to a completely different page when I click on it, or is it meant as you fetch data from some articles?

The idea for this US is the following: 
- we will implement an array of objects containing single content pieces. 
- The page for "Plant Tips" shall then contain card-elements which link to Plant Tip Details Pages. 
- We don't want to fetch data from external articles.
- When clicking on a "card" on the "Plant Tips" page, the user will be redirected to the [id] page of the plant tips.

So basically, this is very similar to the Plants and Plant Details-Pages from US 1 and US 2.

Taking this and your feedback into account, we reworked the last task of the US to better reflect that.


> * Optional: In your wireframe, you use two different labels: the "Plant tips" icon is labeled "`Plant tips`" while the page itself is called "`Tip list`" For consistency, you may want to name them the same, at least in the title.

Yes, indeed. We've updated the wireframes accordingly.

> * Also optional: According to you wireframe it's not visible that it's a slider. Maybe you can show `< >`  on the sides or `...` in the middle that the user can do here something.

Very good point. Based on that feedback we have fundamentally revised the US. We realized that implementing a banner component to the HomePage should be a US on its own. Thus, it's not part of the wireframes of this US anymore.

**Comment by JessicaLoers** [comment]
**Hey Team. ✌️** 

Just a note on the Acceptance Criteria in general.

> There is a js file in the project containing the single "Plant Tips" shown in the app.

ACs should be written from the **user's perspective** and should **not include technical implementation details.** This helps keep the focus on what the user expects to experience rather than how the feature is built.

➡️ Remove this point from ACs, as it specifies an implementation detail.

If you change this, the user story is approved. 🎉

**Comment by StephMode** [comment]
Hi @JessicaLoers , thanks a lot for the hint. We've deleted this AC and will move this US into the Sprint Backlog 👍🏼
