### ISSUE TITLE
#10 - Clickable PlantCard ✅⏺️

### ISSUE THREAD

**Issue by carmen136** [StephMode/plant-pal#18]
# Clickable plantCard

## Value Proposition

**As a user**
**I want to** click on any part of a plant card,
**so that**  I can easily navigate to the details of a plant I am interested in learning more about.

## Description

![Image](https://github.com/user-attachments/assets/cf9b1de9-d213-43a5-a1a9-4eab154422d2)

## Acceptance Criteria

- Each of the following elements should serve as a link to the details page of the respective plant: **plant name, botanical name, plant image**
- The bookmark button is excluded from this functionality
- On desktop, the plant card should turn the cursor into a pointer when moving the mouse onto a plant card

## Tasks
- [x] Create feature branch `{name}-feature-13-clickable-plantcard`
- [x] Implement a Link function to the plant card
- [x] Develop the Link functionality of the plant card in a way that it does not interfere with the bookmark button functionality
- [x] Add styling to the Link so that a cursor pointer appears when the cursor hovers over the plant card
