### ISSUE TITLE
#2 plant details

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#2]
# Plant Details

## Value Proposition

**As a user**

**I want to** access detailed information about each plant,

**so that** I can get a better understanding of the plant's needs and care requirements.

## Description

<img src="https://github.com/user-attachments/assets/862e1c37-4f41-4696-9a54-bc9da844eb4e" height="400" width="auto" />

## Acceptance Criteria

- Each plant in the plant list has a link to a details page.
- Each details page contains:
  - Plant name
  - Plant botanical name
  - Plant image
  - Plant description
  - Plant light needs
  - Plant water needs
  - Plant fertiliser season
- The water needs, light needs and fertiliser seasons are visualised with fitting icons (e.g. empty or full droplets of water).
- The detailed view includes a “back” link, allowing users to easily navigate back to the plant list.

## Tasks

- [x] Create feature branch `feature/plant-details`
- [x] Create `[id].js` to render "PlantDetailsPage"
  - [x] Implement heading "Plant Details"
  - [x] The PlantDetailsPage shall render: "Plant name" & "Plant botanical name" as h2, "Plant image" as img, "Plant description" as p, "Plant light needs" & "Plant water needs" conditionally rendered icons, "Plant fertiliser season" as p
  - [x] Implement "back" `button` with link to `HomePage`
  - [x] Develop logic to conditionally render icons
- [x] Add link to single `PlantCard.js` for `PlantList.js`
  - [x] call a prop `{ id }`
  - [x] in `PlantCard.js`, use prop to add link of single plant to link
  - [x] Nest plant name into `Link`

**Comment by JessicaLoers** [comment]
In the wireframe, it’s not entirely clear what links to the details page. 

IIf the entire card is intended as a link, bookmarking a specific plant could become challenging, especially as this button will likely be on the card later and may trigger a redirect when clicked. 

The easiest solution would be to either use the plant’s name as the link or add a separate “Details” button directly within the card. 🙃

**Comment by StephMode** [comment]
Check if router.push might be needed for implememtation of Link into single PlantCard

**Comment by JessicaLoers** [comment]
Nice 👍 

US is approved. ✅
