### ISSUE TITLE
#13 - elements for cross-referencing plants with tips✅ ⏺️⏺️⏺️⏺️ 

### ISSUE THREAD

**Issue by levinthiel** [StephMode/plant-pal#25]
## Value Proposition

As a user
I want to have easy access to tips on a single plant and plants that relate to single plant tips 
so that I can learn more about plant care convieniently.

## Description

![Image](https://github.com/user-attachments/assets/431c618f-dec0-4f98-a66e-7492a21a9f40)

## Acceptance Criteria

- On a single `PlantTip` page and on a single `PlantDetails` page, there are small clickable elements resembling "hashtags".
- Every `PlantTip` page contains at least one "hashtag" to a `PlantDetails` page 
- As there are only a few plant tips in the app at this stage, not every `PlantDetails`page must contain "hashtags" to `PlantTips`detail pages.
- Cross-references between single plant tips and plants can be random at this stage.
- There are tags on each `PlantTip` page acting as a Link to a `PlantDetails` page. The tags contain:
  - Small image of the plant  
  - Name of the plant
- There are tags on single `PlantDetails` pages acting as a Link to a `PlantTip` page. The tags contain:
  - Small image of the plant tip
  - Title of the plant tip
- The tag elements on each `PlantDetails` or `PlantTip` page have a heading describing the purpose of the items.

## Tasks

- [x] create feature branch `{name}-feature-#-cross-referencing`
- [x] Implement cross-referencing into data of plants and plant tips
- [x] Develop component for the tag elements
- [x] Implement the component on both `PlantDetails` and `PlantTips` detail page
- [x] Make the single tag element render on `PlantDetail` or `PlantTip` pages respectively

**Comment by levinthiel** [comment]
For the back button, we should use this : 
const router = useRouter()

onClick={() => router.back()}
