### ISSUE TITLE
#14 - Add banner for plant tips ✅⏺️

### ISSUE THREAD

**Issue by levinthiel** [StephMode/plant-pal#26]
# Page with tips for plant care

## Value Proposition

As a user

I want to have easy access to curated plant care tips,

so that I can quickly find inspiration to read some articles about plant care.

## Description

![Image](https://github.com/user-attachments/assets/9834f9da-7052-4b4f-97b5-aa59087daf87)

## Acceptance Criteria

- On the homepage there is a small Banner as preview for a PlantTip.
- The Banner takes full width of the UI and half the height of other items on the `HomePage`
- The Banner contains 
  - the title of the tip.
  - a small version of the image of the tip.
  - A teaser text for the article content it links to.
- The Banner links to the single PlantTip on click.
- The PlantTip shall be randomized upon every reload of the `HomePage`

## Task

- [x] Create a feature branch `person name-feature-add-banner-for-plant-tips`
- [x] Create a component `Banner` to render the Banner for plant tips
- [x] Implement `useEffect` hook and logic, so that a random tip is displayed upon every render
- [x] Add the `Banner` component to the `HomePage`
