### ISSUE TITLE
#3 mark plant as owned✅

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#3]
# Mark Plants as Owned

## Value Proposition

**As a user**

**I want to** mark the plants I own,

**so that** I can easily track and manage the care of my personal collection.

## Description

Capstone Group Todo: Add wireframes

![Image](https://github.com/user-attachments/assets/ba514613-81b7-4a9a-b1f8-0d00ea0928ea)

## Acceptance Criteria

- Each listed plant includes a “Mark as Owned” option.
- Clicking the “Mark as Owned” button of an unmarked plant adds it to the “My Plants” list.
- Clicking the same button again removes the plant from the “My Plants” list.
- The “My Plants” list is displayed on a separate page dedicated to owned plants.
- There is a clearly visible link on the homepage to navigate to the “My Plants” page.
- There is a clearly visible link on the “My Plants” page to navigate back to the homepage.
- Owned plants are visually highlighted by a distinct icon or style to differentiate them from unowned plants.
- If there are no owned plants in the “My Plants” list, a message is displayed to the user indicating that no plants have been marked as owned.

## Tasks

- [x] Create feature branch `feature/mark-as-owned`
- [x] Create comp `PlantOwnedButton.js`
  - [x] implement SVG for button
  - [x] conditional return statement: isOwned? "full star" : "empty star"
  - [x] call props `{isOwned, handleToggleOwned, plantId }`
- [x] Develop handle toggle function in `App.js` to toggle isOwned
- [x] Create page `MyPlants.js`
  - [x] Add header "My Plants"
  - [x] conditional return statement: isOwned? display list of all owned plants : "No plants on list"
  - [x] Utilize `.filter` to iterate over `plants`-state and return `PlantCard`(s) if `isOwned=true`
- [x] Implements link to navigate between `HomePage` and `MyPlants`

**Comment by JessicaLoers** [comment]
Yeah. Nice one ✨
