### ISSUE TITLE
#18 - Create an intro page ✅⏺️

### ISSUE THREAD

**Issue by levinthiel** [StephMode/plant-pal#33]
# Intro Page

## Value Proposition

**As a Plant friend**

**I want to** have an introduction page to my app

**so that** I can get in the mood and have a bit of a design preview.

## Description

![Image](https://github.com/user-attachments/assets/5af8f361-019c-4817-9a65-3405eda6ba69)

## Acceptance Criteria

- The Intro page has the logo of the app
- The page has a short intro text
- The user is automatically redirected to the home page after a give interval

## Tasks

- [ ] Create feature branch 
- [ ] Create an Intro page with background, logo, and text
- [ ] create the redirect to the home page
