### ISSUE TITLE
#19 - Add breadcrumbs and update navi active if needed ✅⏺️⏺️⏺️

### ISSUE THREAD

**Issue by levinthiel** [StephMode/plant-pal#34]
# Breadcrumbs

## Value Proposition

**As a plant aficionado**
**I want to** see breadcrumbs on relevant pages 
**so that** I can situate myself better within the app
## Description

![Image](https://github.com/user-attachments/assets/06755ec3-0fdc-4f9c-bfa6-3535a926183a)

## Acceptance Criteria

- The breadcrumbs are present in the first third of the page for better visibility
- each part of the breadcrumb is a clickable link
- The breadcrumbs update depending on which page the user is 
- The breadcrumbs are present on two types of pages: plant details & tip details

## Tasks

- [x] Create feature branch
- [x] Create a breadcrumb component
- [x] Create flexible links within the component so it automatically updates itself
- [x] implement the component on relevant pages
