### ISSUE TITLE
#20 search bar ✅ ⏺️⏺️⏺️⏺️

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#36]
## Value Proposition

As a user
I would like to search through plants and care tips
So that I can find what I am looking for more easily

## Description

Please note: for the sake of clarity, the wireframe represents the feature only on the homepage for plants, as the structure of the homepage for care tips is very similar.

![Image](https://github.com/user-attachments/assets/2f4fd326-ae16-4dd4-8cd1-2ecd50f3d00e)

## Acceptance Criteria

- A search bar is present on top of:
  - the homepage listing all plants.
  - the page listing all care tips.
- The list of card items updates dynamically as the user types.
- Only **plants** or **care tips** matching the search query are displayed.
- If no **plant** or **care tip** match the search query, a message with user-friendly text is displayed.
- Clearing the search bar restores the full list of **plants** or **care tips**.
- The search is case-insensitive.
- The search matches the following attributes:
  - **plants**: name and botanical name
  - **care tips**: title and short description

## Tasks

- [x] create feature branch
- [x] research different types of search (e.g. fuzzy, throttling)
- [x] Develop a `SearchBar` component
- [x] Implement `SearchBar` component on plant list page and the care tips page.
