### ISSUE TITLE
Set custom reminders ✅⏺️⏺️⏺️⏺️

### ISSUE THREAD

**Issue by carmen136** [StephMode/plant-pal#38]
## Value Proposition

**As a user**

**I want** to set custom reminders for plant care tasks

**So  that** I will be reminded to take care of my plants effectively.

## Description

![Image](https://github.com/user-attachments/assets/8eb8a7aa-bd90-4993-8d6e-a84cb03fc356)
![Image](https://github.com/user-attachments/assets/f2a36443-a655-4a66-badc-1e576477f833)

## Acceptance Criteria

- Users can set personalized reminders for plants by 
  - writing the task (e.g. watering)
  - setting a due date for the task
- The reminders appear on the detail page of the respective plant.
- There's a reminders page providing an overview of all reminders. Each reminder on the page displays:
  - plant's name
  - care task
  - due date
- When multiple reminders exist, they are organized by their due dates.
- When Users mark a reminder as "done", reminders are removed both on the reminders page and the respective plant details page.
- A notification icon appears in the footer if there are any reminders set to the present date

## Tasks

- [x] Create feature branch {name}-feature-set-custom-reminders
- [x] Create dataset to store reminder data
- [x] Implement page for "Reminders"
  - [x] add Link to `Navbar` for "Reminders" page
- [x] Create `ReminderCard` component
- [x] Create `ReminderForm` component
- [x] Implement Toast Message when adding new reminder 
- [x] Implement `Button` on `PlantDetailsPage` to add reminders
- [x] Reuse `Modal` component to display and hide `ReminderForm`
- [x] Develop notification when reminder is set to the present date

**Comment by IboNdure** [comment]
LGTM nice job and well done  is approved! 
 Only this "Create structure to store reminder data"
maybe u can define it more precisly
