### ISSUE TITLE
#4 create plant✅

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#4]
# Create Plant

## Value Proposition

**As a user**

**I want to** create and store new plants,

**so that** I can personalise and expand the plant selection to better reflect my collection and preferences.

## Description

![Image](https://github.com/user-attachments/assets/6cef5201-979e-4656-8d32-93343d6243f5)

![Image](https://github.com/user-attachments/assets/7045c011-d3c3-45bb-aff5-5acebdac9c5c)

## Acceptance Criteria

- A form for adding plants is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Plant name
  - Plant botanical name
  - Plant description
  - Plant light needs
  - Plant water needs
  - Plant fertiliser season
- The following fields are mandatory:
  - Plant name
  - Plant botanical name
  - Plant light needs
  - Plant water needs
- The light needs are selected via radio buttons with the options: Full Sun, Partial Shade, Full Shade.
- The water needs are selected via radio buttons with the options: Low, Medium, High.
- The fertiliser season is selected via checkboxes, allowing multiple selections with the options: Spring, Summer, Autumn, Winter.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new plant is added to the top of the plant list.

## Tasks

- [x] Create feature branch `feature/create-plant`
- [x] Implement an `AddPlantForm` component that allows users to add a new plant to `plants`-state
- [x] Add header "Add Plant"
- [x] Add input fields & labels: "Plant name" (required), "Plant botanical name" `text` (required), "Plant description" `textarea`,"Plant light needs" (required) & "Plant water needs" `radio` (required), "Plant fertiliser season" `checkbox`
  - [x] add a placeholder for every input field
- [x] Manage formData not submitted by user
  - [x] Use a package to generate unique id's like [nanoid](https://www.npmjs.com/package/nanoid) or [ui](https://www.npmjs.com/package/uid)
  - [x] add a generic URL for imageURL
- [x] Add `submit` button to add a new plant with the data from the form
- [x] develop a function which handles the form submit, prevent the default behaviour and implement a form reset
- [x] Implement 'AddPlantForm' on 'HomePage'
- [x] develop function and call props to handle the `plants` state

> 💡 It is not yet possible to add images at this stage. For this reason, a placeholder image should be saved when creating a plant.

**Comment by Leon910** [comment]
Hi @StephMode! Great User Story so far but also very comprehensive regarding to your wireframe! I have some suggestions you could consider to add or think about it:

- Add a specific task for managing validation for mandatory fields: you could think of adding required fields as well as a hint-message after the user clickied submit that he hasn´t yet input all the mandatory fields e.g.
- There is more to the submit functionality than just the submit-button: you could think of describing the tasks for a submit-handler function e.g.
- Would be a form-reset also an option for you after successful submitting?
- If you want to include a placeholder you maybe also should describe the tasks for that: do you want to fetch it from an external website  or where does it come from?
- Consider to create the "AddPlantForm" as a separate component 
- Your wireframe implies that the form is appearing after clicking the add plant button. I think this is a whole new UserStory and should be excluded from this User Story because the main feature is to create a new plant - consider not to put too many features or functionality within one User Story

Also could you upload the wireframe with a higher resolution? Not all of the text is readable.

**Comment by levinthiel** [comment]
Hi @Leon910, thanks for the review. 
we're working on it.

**Comment by predrag-babic** [comment]
Hi,
nice US :)
I have small suggestions you could consider to change.

* I suppose you want to add bookmark in later stage, and when you bookmarked plants, you can see them in footer nav in "My plants"?
In this US you don´t have this functionality yet, and i would suggest that you take it out, and update your wireframe.

* In your task you can maybe write how do you want to achieve adding new plant ( add function).

**Comment by levinthiel** [comment]
Hi @predrag-babic,
thanks for your feedback. 
The bookmark button is in the wireframe because the functionality was already created in our US - 3. 
About the second point, we explain it in our third and second last points of the task, but we updated the text a little so it's more comprehensive.

**Comment by ahohnsen** [comment]
Great work.

As mentioned in one of the previous comments, I recommend adding higher-resolution wireframes to your user stories in the future, as the individual elements are difficult to see otherwise.
