### ISSUE TITLE
refactor Search

### ISSUE THREAD

**Issue by StephMode** [StephMode/plant-pal#53]
# Developer Story

Search is in the product now.
It works, but causes minor bugs and issues both in front end and when compiling.
The code needs refactoring to decrease build time and simplify logic.

# Overview

The search feature works for the most part in the front end. However, we ran into issues in production:
- there seems to be a bug when the user tries to first search and then bookmark plants or vice versa.
- build time is quite slow ( see reference).

While the the feature and the component works, the logic is subpar due to overreliance on `useState` and `useEffect`. 
We got comprehensive feedback, see code review of PR https://github.com/StephMode/plant-pal/pull/51.

This means we need to:
- refactor the code so that the logic works on props and not states for the most part.
- find alternatives to utilizing `useEffect` in `app.js` and `Search` for the feature (see references).
- rethink how to set the value of renderable plants/tips of the .map functions.

We should look into this possible way of refactoring:
- create `utils.js` in public
- delete state searchResult
- lift `searchResult` state management from `app.js` to `utils.js`
- rename `searchResult` state management to something like `writeSearchResult` (it should write a `const` instead)
- call `writeSearchResult` in `app.js` or maybe more locally in `HomePage` and `plantTipsPage`
> !! This might be necessary due to the fact that there is more than 1 page where we want the user to be able to search.

# Tasks

- [ ] create a `{name}-refactor-` branch
- [ ] Refactor logic so that `useEffect` is not needed anymore
- [ ] Refactor `searchResult` logic so that `useEffect` is not needed anymore
- [ ] Find solutions to decrease the number of states

# References

## Reference for build time:

```
> plant-pal@0.0.0-unreleased dev
> next dev

   ▲ Next.js 15.0.2
   - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1122ms
```

### states for `Search` in `app.js`
```
  const [searchQuery, setSearchQuery] = useState("");
  const [searchPage, setSearchPage] = useState(""); 
  const [searchResults, setSearchResults] = useState([]);
  const [noSearchResults, setNoSearchResults] = useState(false);
```

### `useEffect` in `Search` for resetSearch

```
    useEffect(() => {
        resetSearch();
    }, [searchFor])
```

###  `searchResult` state management in `app.js` using `useEffect`

https://github.com/StephMode/plant-pal/blob/187712bf925d6ab24ab2bdce55994d9c42f8d5e6/pages/_app.js#L255-L276
